version: "3.8"
services:
    web:
      build: ./ufc_rankings
    #   command: flask run
      volumes:
        # - ./ufc_rankings/:/usr/src/ufc_rankings/
        - .:/code
      ports:
        - 5000:5000
      environment:
        - DB_NAME=ufc_rankings_db
        - DB_USER=postgres
        - DB_PASSWORD=admin123
        - DB_HOST=pg
        - DB_PORT=5432
        - DATABASE=postgres
      depends_on:
        - pg

    pg:
        container_name: pg_container
        image: postgres:13.2-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: ufc_rankings_db
            POSTGRES_HOST_AUTH_METHOD: trust
            PGUSER: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./data:/data
            - ./data/misc/flask_init.sql:/docker-entrypoint-initdb.d/1-init.sql
            # - ./data/ufc_rankings/init.sql:/docker-entrypoint-initdb.d/2-init.sql
            # - ./data/moma/init.sql:/docker-entrypoint-initdb.d/3-init.sql
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:5.2
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin123
            PGADMIN_LISTEN_PORT: 5433
            PGADMIN_CONFIG_SERVER_MODE: "False"
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
            PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
        ports:
            - "5433:5433"
        depends_on:
            - pg
networks:
    default:
        name: nunet
